/**
 * The static demo's economic loop.
 *
 * The published site runs with no backend, so the loop half of the product —
 * status, attention, opportunities, ROI — has nothing to render from. This
 * snapshot mirrors the shapes the engine's reports return, so the demo can
 * show the whole loop a visitor would otherwise never see. It is illustrative,
 * not fabricated-as-live: the demo mode labels it "sample data".
 */

export interface DemoOpportunity {
  id: string;
  title: string;
  capability: string;
  kind: string;
  burden: {
    interventions_month: number;
    human_hours_month: number;
    attention_dollars_month: number;
  };
  proposal: { action: string; setup_hours: number };
  expected: { human_hours_month_after: number; savings_dollars_month: number };
  payback_months: number;
  confidence: 'high' | 'medium' | 'low';
  acquisition_options?: {
    provider: string;
    kind: string;
    total_first_year_dollars?: number;
    privacy: string;
  }[];
}

export interface DemoSnapshot {
  status: {
    reached: number;
    total: number;
    verified: number;
    failing: number;
    degraded: string[];
    spofs: string[];
    deficits: string[];
    pending: { id: string; goal: string }[];
  };
  attention: {
    interventions: number;
    reducible: {
      kind: string;
      capability: string;
      times: number;
      hours: number;
      suggested_fix: string;
    }[];
    keepers: { kind: string; capability: string; times: number }[];
  };
  opportunities: DemoOpportunity[];
  roi: { hours_per_year: number; dollars_per_year: number; accuracy: number; verdict: string };
}

/**
 * The illustrative snapshot a visitor sees in LOOP view.
 *
 * Hand-authored, unlike demo-data.json beside it, and deliberately so. The
 * setup and tree views are *derived* — one fixture config through the engine,
 * regenerated by `npm run demo:generate` — because they are things the engine
 * computes from a config. This is not: it is a work ledger with recorded
 * interventions, priced opportunities and realised ROI, which accumulate over
 * months of use. Generating it would mean fabricating that history rather than
 * reading anything, so the numbers are chosen to tell the story the loop is
 * for, and are illustration rather than output.
 */
export function demoSnapshot(): DemoSnapshot {
  return {
    status: {
      reached: 46,
      total: 49,
      verified: 38,
      failing: 1,
      degraded: ['E2E on Edge'],
      spofs: ['Version Control', 'Local Inference', 'Secret Management'],
      deficits: ['Vector Store — blocked 4×, structural'],
      pending: [{ id: 'prop-msrv0x', goal: 'Automate invoice retrieval' }],
    },
    attention: {
      interventions: 84,
      reducible: [
        {
          kind: 'clerical',
          capability: 'Manual data transfer',
          times: 39,
          hours: 3.2,
          suggested_fix: 'the transfer is mechanical — automate it end to end',
        },
        {
          kind: 'authority',
          capability: 'Deploy to production',
          times: 31,
          hours: 0.7,
          suggested_fix: 'grant bounded authority rather than approving each time',
        },
        {
          kind: 'exception',
          capability: 'Payment anomaly',
          times: 7,
          hours: 1.9,
          suggested_fix: 'the case recurs — encode the handling as a capability',
        },
      ],
      keepers: [{ kind: 'judgment', capability: 'Architecture review', times: 12 }],
    },
    opportunities: [
      {
        id: 'opp-1',
        title: 'Automate invoice retrieval',
        capability: 'Invoice retrieval',
        kind: 'clerical',
        burden: { interventions_month: 43, human_hours_month: 8.6, attention_dollars_month: 2150 },
        proposal: { action: 'acquire combo:invoice-retrieval', setup_hours: 3.5 },
        expected: { human_hours_month_after: 0.8, savings_dollars_month: 1935 },
        payback_months: 0.6,
        confidence: 'high',
        acquisition_options: [
          {
            provider: 'SaaS provider',
            kind: 'subscribe',
            total_first_year_dollars: 5880,
            privacy: 'hosted',
          },
          {
            provider: 'API integration',
            kind: 'build',
            total_first_year_dollars: 4560,
            privacy: 'local',
          },
        ],
      },
      {
        id: 'opp-2',
        title: 'Automate manual data transfer',
        capability: 'Data transfer',
        kind: 'clerical',
        burden: { interventions_month: 39, human_hours_month: 3.2, attention_dollars_month: 800 },
        proposal: { action: 'acquire combo:automated-transfer', setup_hours: 2 },
        expected: { human_hours_month_after: 0.3, savings_dollars_month: 720 },
        payback_months: 0.7,
        confidence: 'high',
      },
      {
        id: 'opp-3',
        title: 'Acquire a vector store',
        capability: 'Vector store',
        kind: 'deficit',
        burden: { interventions_month: 4, human_hours_month: 1.1, attention_dollars_month: 275 },
        proposal: { action: 'acquire combo:vector-store', setup_hours: 0.5 },
        expected: { human_hours_month_after: 0.1, savings_dollars_month: 248 },
        payback_months: 0.3,
        confidence: 'medium',
      },
    ],
    roi: {
      hours_per_year: 41,
      dollars_per_year: 9600,
      accuracy: 1.1,
      verdict: 'performing near forecast',
    },
  };
}

/** The sample graph JSON a static visitor can PASTE — mirrors `ambit graph`. */
export function demoGraphExport(): string {
  return JSON.stringify(
    {
      items: [
        {
          id: 'opencode-core',
          name: 'OpenCode',
          type: 'framework',
          status: 'built',
          description: 'Main framework',
          meta: { domain: 'meta' },
        },
        {
          id: 'mcp:playwright',
          name: 'Playwright',
          type: 'mcp-server',
          status: 'built',
          description: 'Browser automation',
          meta: { domain: 'quality' },
        },
        {
          id: 'mcp:cloudflare',
          name: 'Cloudflare',
          type: 'mcp-server',
          status: 'built',
          description: 'Edge compute',
          meta: { domain: 'backend' },
        },
        {
          id: 'mcp:github',
          name: 'GitHub',
          type: 'mcp-server',
          status: 'built',
          description: 'CI + repos',
          meta: { domain: 'devops' },
        },
        {
          id: 'mcp:tailscale',
          name: 'Tailscale',
          type: 'mcp-server',
          status: 'built',
          description: 'Mesh VPN',
          meta: { domain: 'infra' },
        },
        {
          id: 'mcp:brew',
          name: 'Homebrew',
          type: 'mcp-server',
          status: 'built',
          description: 'Packages',
          meta: { domain: 'devops' },
        },
        {
          id: 'mcp:1password',
          name: '1Password',
          type: 'mcp-server',
          status: 'built',
          description: 'Secrets',
          meta: { domain: 'security' },
        },
        {
          id: 'agent:oracle',
          name: 'Oracle',
          type: 'agent',
          status: 'built',
          description: 'Debugging',
          meta: { domain: 'meta' },
        },
        {
          id: 'agent:steward',
          name: 'Steward',
          type: 'agent',
          status: 'built',
          description: 'Repos',
          meta: { domain: 'devops' },
        },
        {
          id: 'skill:cloudflare',
          name: 'Cloudflare',
          type: 'skill',
          status: 'built',
          description: 'Workers',
          meta: { domain: 'backend' },
        },
        {
          id: 'skill:wrangler',
          name: 'Wrangler',
          type: 'skill',
          status: 'built',
          description: 'CLI',
          meta: { domain: 'backend' },
        },
        {
          id: 'skill:vitest',
          name: 'Vitest',
          type: 'skill',
          status: 'built',
          description: 'Unit tests',
          meta: { domain: 'quality' },
        },
        {
          id: 'skill:durable-objects',
          name: 'Durable Objects',
          type: 'skill',
          status: 'specified',
          description: 'Stateful',
          meta: { domain: 'backend' },
        },
        {
          id: 'combo:e2e',
          name: 'E2E on Edge',
          type: 'possibility',
          status: 'specified',
          description: 'Deploy + verify at the edge',
          meta: { domain: 'quality' },
        },
        {
          id: 'combo:deploy',
          name: 'Deploy Pipeline',
          type: 'possibility',
          status: 'specified',
          description: 'Push → build → verify',
          meta: { domain: 'devops' },
        },
        {
          id: 'combo:local-ai',
          name: 'Local Inference',
          type: 'possibility',
          status: 'built',
          description: 'Quantized models on your own hardware',
          meta: { domain: 'ai-ml' },
        },
        {
          id: 'tool:bash',
          name: 'Shell',
          type: 'framework',
          status: 'built',
          description: 'Commands',
          meta: { domain: 'infra' },
        },
      ],
      connections: [
        { from: 'opencode-core', to: 'mcp:playwright', type: 'connects' },
        { from: 'opencode-core', to: 'mcp:cloudflare', type: 'connects' },
        { from: 'opencode-core', to: 'mcp:github', type: 'connects' },
        { from: 'opencode-core', to: 'agent:oracle', type: 'subagent' },
        { from: 'skill:cloudflare', to: 'combo:e2e', type: 'hard-dep' },
        { from: 'skill:vitest', to: 'combo:e2e', type: 'hard-dep' },
        { from: 'skill:cloudflare', to: 'combo:deploy', type: 'hard-dep' },
        { from: 'skill:wrangler', to: 'combo:deploy', type: 'hard-dep' },
        { from: 'mcp:cloudflare', to: 'combo:e2e', type: 'soft-dep' },
        { from: 'mcp:playwright', to: 'combo:e2e', type: 'soft-dep' },
      ],
    },
    null,
    2
  );
}
