/**
 * The static demo's economic loop.
 *
 * The published site runs with no backend, so the loop half of the product —
 * status, attention, opportunities, ROI — has nothing to render from. This
 * snapshot is the shape `/api/loop` returns on a machine with a ledger, so the
 * demo can show the whole loop a visitor would otherwise never see. It is
 * illustrative, not fabricated-as-live: the page labels it sample data.
 */
import type { LoopSnapshot } from '../../shared/api';

/**
 * The illustrative snapshot a visitor sees in LOOP view.
 *
 * Hand-authored, unlike demo-data.json beside it, and deliberately so. The
 * setup and tree views are *derived* — one fixture config through the engine,
 * regenerated by `npm run demo:generate` — because they are things the engine
 * computes from a config. This is not: it is a work ledger with recorded
 * interventions, priced opportunities and realised ROI, which accumulate over
 * months of use. Generating it would mean fabricating that history rather than
 * reading anything, so the numbers are chosen to tell the story the loop is
 * for, and are illustration rather than output.
 */
export function demoSnapshot(): LoopSnapshot {
  return {
    status: {
      reached: 46,
      total: 49,
      verified: 38,
      failing: 1,
      degraded: ['E2E on Edge'],
      spofs: ['Version Control', 'Local Inference', 'Secret Management'],
      deficits: ['Vector Store — blocked 4×, structural'],
      pending: [{ id: 'prop-msrv0x', goal: 'Automate invoice retrieval' }],
    },
    attention: {
      interventions: 89,
      reducible: [
        {
          kind: 'clerical',
          capability: 'Manual data transfer',
          capability_id: 'combo:data-access',
          times: 39,
          hours: 3.2,
          suggested_fix: 'the transfer is mechanical — automate it end to end',
        },
        {
          kind: 'authority',
          capability: 'Deploy to production',
          capability_id: 'combo:continuous-delivery',
          times: 31,
          hours: 0.7,
          suggested_fix: 'grant bounded authority rather than approving each time',
        },
        {
          kind: 'exception',
          capability: 'Payment anomaly',
          capability_id: 'combo:observability',
          times: 7,
          hours: 1.9,
          suggested_fix: 'the case recurs — encode the handling as a capability',
        },
      ],
      keepers: [
        {
          kind: 'judgment',
          capability: 'Architecture review',
          capability_id: 'combo:code-intelligence',
          times: 12,
          hours: 2.4,
        },
      ],
    },
    opportunities: [
      {
        id: 'opp-1',
        title: 'Automate invoice retrieval',
        capability: 'Invoice retrieval',
        // Scheduled Work is what retrieving invoices on a timer *is*, and the
        // series below already credits it with October's drop. Every row here
        // names a node the demo graph holds, so "Map" lands on the thing the
        // row is about rather than on whatever the id happened to match.
        capability_id: 'combo:scheduled-work',
        kind: 'clerical',
        burden: { interventions_month: 43, human_hours_month: 8.6, attention_dollars_month: 2150 },
        proposal: { action: 'acquire combo:invoice-retrieval', setup_hours: 3.5 },
        expected: { human_hours_month_after: 0.8, savings_dollars_month: 1935 },
        payback_months: 0.6,
        confidence: 'high',
        acquisition_options: [
          {
            provider: 'SaaS provider',
            kind: 'subscribe',
            total_first_year_dollars: 5880,
            privacy: 'hosted',
          },
          {
            provider: 'API integration',
            kind: 'build',
            total_first_year_dollars: 4560,
            privacy: 'local',
          },
        ],
      },
      {
        id: 'opp-2',
        title: 'Automate manual data transfer',
        capability: 'Data transfer',
        capability_id: 'combo:data-access',
        kind: 'clerical',
        burden: { interventions_month: 39, human_hours_month: 3.2, attention_dollars_month: 800 },
        proposal: { action: 'acquire combo:automated-transfer', setup_hours: 2 },
        expected: { human_hours_month_after: 0.3, savings_dollars_month: 720 },
        payback_months: 0.7,
        confidence: 'high',
      },
      {
        id: 'opp-3',
        title: 'Acquire a vector store',
        capability: 'Vector store',
        capability_id: 'combo:vector-store',
        kind: 'deficit',
        burden: { interventions_month: 4, human_hours_month: 1.1, attention_dollars_month: 275 },
        proposal: { action: 'acquire combo:vector-store', setup_hours: 0.5 },
        expected: { human_hours_month_after: 0.1, savings_dollars_month: 248 },
        payback_months: 0.3,
        confidence: 'medium',
      },
    ],
    roi: {
      hours_per_year: 41,
      dollars_per_year: 9600,
      accuracy: 1.1,
      verdict: 'performing near forecast',
      // Twelve months against January's 11.0h: the gap sums to the 41 hours
      // above, so the picture and the headline are the same claim.
      monthly_hours: [
        { month: 'Jan', hours: 11.0 },
        { month: 'Feb', hours: 10.4 },
        { month: 'Mar', hours: 10.2 },
        { month: 'Apr', hours: 9.1, acquired: 'Automated Tests' },
        { month: 'May', hours: 8.6 },
        { month: 'Jun', hours: 7.9 },
        { month: 'Jul', hours: 7.2 },
        { month: 'Aug', hours: 6.8 },
        { month: 'Sep', hours: 6.4 },
        { month: 'Oct', hours: 5.1, acquired: 'Scheduled Work' },
        { month: 'Nov', hours: 4.3 },
        { month: 'Dec', hours: 4.0 },
      ],
      forecast: { predicted_hours: 37, observed_hours: 41 },
    },
  };
}
